apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: prod
  labels:
    app: search_engine
    component: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: crawler
  template:
    metadata:
      name: crawler
      labels:
        app: search_engine
        component: crawler
    spec:
      containers:
      - image: sspyataev/search_engine_crawler:latest
        name: crawler
        env:
        - name: MONGO
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: RMQ_HOST
          value: rabbitmq
        - name: RMQ_QUEUE
          value: crawler_queue
        - name: RMQ_USERNAME
          value: user
        - name: RMQ_PASSWORD
          value: password
        - name: CHECK_INTERVAL
          value: "100"
