apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: prod
  labels:
    app: search_engine
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: ui
  template:
    metadata:
      name: ui
      labels:
        app: search_engine
        component: ui
    spec:
      containers:
      - image: sspyataev/search_engine_ui:latest
        name: ui
        env:
        - name: MONGO
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
