apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: prod
  labels:
    component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    component: rabbitmq
