apiVersion: v1
kind: Service
metadata:
  name: crawler
  namespace: prod
  labels:
    app: search_engine
    component: crawler
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: search_engine
    component: crawler
