apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: prod
  labels:
    app: search_engine
    component: ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: search_engine
    component: ui
