name: my awesome workflow
on: [push]
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
        
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
        
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker/search_engine_crawler
          file: docker/search_engine_crawler/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/search_engine_crawler
