name: my awesome workflow
on: [push]
jobs:
  # build-and-push-images:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: check out the repo
  #       uses: actions/checkout@v2
        
  #     - name: set up qemu
  #       uses: docker/setup-qemu-action@v1
        
  #     - name: set up docker buildx
  #       uses: docker/setup-buildx-action@v1
        
  #     - name: login to dockerhub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
          
  #     - name: build and push crawler
  #       id: docker_build_crawler
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: docker/search_engine_crawler
  #         file: docker/search_engine_crawler/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/search_engine_crawler

  #     - name: build and push ui
  #       id: docker_build_ui
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: docker/search_engine_ui
  #         file: docker/search_engine_ui/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/search_engine_ui

  # create_cluster:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: terraform
  #   steps:
  #     - name: check out the repo
  #       uses: actions/checkout@v2

  #     - name: setup terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  #     - name: terraform init
  #       run: terraform init

  #     - name: terraform apply
  #       run: terraform apply -auto-approve=true

  deploy_application:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      
      - name: setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}