name: my awesome workflow
on: [push]
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2
      - name: login to docker registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: hub.docker.com  
      - name: build image
        run: |
          cd docker/search_engine_crawler
          docker build -t ${ DOCKER_USERNAME }/search_engine_crawler:latest
      - name: push image
        uses: actions-hub/docker@master
        with:
          args: push ${ DOCKER_USERNAME }/search_engine_crawler:latest
          
